name: Update PL data

on:
  schedule:
    - cron: "0 7 * * *"   # 09:00 svensk tid
    - cron: "0 14 * * *"  # 16:00 svensk tid
    - cron: "0 18 * * *"  # 20:00 svensk tid
    - cron: "30 21 * * *" # 23:30 svensk tid

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta repository
        uses: actions/checkout@v4

      - name: Installera Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installera dependencies
        run: pip install requests pandas matplotlib

      - name: Kör Python-scriptet
        run: python PL_project.py

      - name: Spara ny data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/pl_data.json
          git commit -m "Update PL data" || echo "No changes"
          git push